export const messengerThemes = [
  {
    id: "light",
    name: "Light Mode",
    colors: {
      bg: "#f5f6f7",
      messageOutgoingBg: "#0084ff",
      messageIncomingBg: "#ffffff",
      messageOutgoingText: "#ffffff",
      messageIncomingText: "#000000",
      messageText: "#000000",
      accent: "#1877f2",
      secondaryText: "#65676b",
    },
  },
  {
    id: "dark",
    name: "Dark Mode",
    colors: {
      bg: "#0f0f0f",
      messageOutgoingBg: "#0084ff",
      messageIncomingBg: "#2a2a2a",
      messageText: "#ffffff",
      accent: "#0084ff",
      secondaryText: "#a3a3a3",
    },
  },
  {
    id: "midnight",
    name: "Midnight Purple",
    colors: {
      bg: "#1a001f",
      messageOutgoingBg: "#8e2de2",
      messageIncomingBg: "#3b0063",
      messageText: "#ffffff",
      accent: "#a91079",
      secondaryText: "#d9a7c7",
    },
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    colors: {
      bg: "#e3f2fd",
      messageOutgoingBg: "#0077b6",
      messageIncomingBg: "#90e0ef",
      messageText: "#0a0a0a",
      accent: "#00b4d8",
      secondaryText: "#555555",
    },
  },
  {
    id: "sunset",
    name: "Sunset Glow",
    colors: {
      bg: "#fff1e6",
      messageOutgoingBg: "#ff5f6d",
      messageIncomingBg: "#ffc371",
      messageText: "#2e2e2e",
      accent: "#ff7e5f",
      secondaryText: "#444444",
    },
  },
  {
    id: "forest",
    name: "Forest Green",
    colors: {
      bg: "#e8f5e9",
      messageOutgoingBg: "#1b5e20",
      messageIncomingBg: "#a5d6a7",
      messageText: "#ffffff",
      accent: "#43a047",
      secondaryText: "#4e4e4e",
    },
  },
  {
    id: "pastel",
    name: "Pastel Dream",
    colors: {
      bg: "#faf3f3",
      messageOutgoingBg: "#b5ead7",
      messageIncomingBg: "#c7ceea",
      messageText: "#222222",
      accent: "#ffdac1",
      secondaryText: "#666666",
    },
  },
  {
    id: "rose",
    name: "Rose Blush",
    colors: {
      bg: "#fff0f5",
      messageOutgoingBg: "#ff85a1",
      messageIncomingBg: "#ffe6ea",
      messageText: "#1a1a1a",
      accent: "#ff3366",
      secondaryText: "#555555",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk Neon",
    colors: {
      bg: "#0d0221",
      messageOutgoingBg: "#ff007f",
      messageIncomingBg: "#3f0071",
      messageText: "#ffffff",
      accent: "#00fff0",
      secondaryText: "#a1a1a1",
    },
  },
  {
    id: "autumn",
    name: "Autumn Amber",
    colors: {
      bg: "#fff8e1",
      messageOutgoingBg: "#ff8f00",
      messageIncomingBg: "#ffe082",
      messageText: "#2e2e2e",
      accent: "#ffb300",
      secondaryText: "#5d4037",
    },
  },
];
